name: Add TV Series
description: Add a new TV series to the repository
body:
  - type: markdown
    attributes:
      value: |
        **[ADD-TV-SERIES]** Thanks for contributing! Please fill out the form below to add a new TV series.

  - type: input
    id: series-title
    attributes:
      label: Series Title
      description: Enter the full title of the TV series
      placeholder: e.g., Breaking Bad
    validations:
      required: true

  - type: input
    id: series-year
    attributes:
      label: Release Year
      description: Enter the year the series started
      placeholder: e.g., 2008
    validations:
      required: true

  - type: input
    id: source-info
    attributes:
      label: Source
      description: Where did you get these streaming links from?
      placeholder: e.g., GitHub Repository, Archive.org, Personal Collection
    validations:
      required: true

  - type: textarea
    id: episodes-data
    attributes:
      label: Episodes URLs
      description: |
        Enter episode URLs using this format:

        ### Season 1
        #### Episodes
        **URLs:**
        - url episode 1
        - url episode 2

        ### Season 2
        #### Episodes
        **URLs:**
        - url episode 1
        - url episode 2
      placeholder: |
        ### Season 1
        #### Episodes
        **URLs:**
        - https://archive.org/download/series/s01e01.mp4
        - https://archive.org/download/series/s01e02.mp4

        ### Season 2
        #### Episodes
        **URLs:**
        - https://archive.org/download/series/s02e01.mp4
        - https://archive.org/download/series/s02e02.mp4
      rows: 50
    validations:
      required: true

  - type: input
    id: imdb-id
    attributes:
      label: IMDB ID (Optional)
      description: IMDB identifier (e.g., tt1234567)
      placeholder: tt0903747
    validations:
      required: false

  - type: input
    id: cover-url
    attributes:
      label: Cover/Poster URL (Optional)
      description: Link to series poster image
      placeholder: https://example.com/poster.jpg
    validations:
      required: false

  - type: textarea
    id: series-summary
    attributes:
      label: Summary (Optional)
      description: Brief description of the series
      placeholder: A brief description of the series...
      rows: 3
    validations:
      required: false

  - type: dropdown
    id: series-status
    attributes:
      label: Series Status (Optional)
      description: Current status of the series
      options:
        - Ongoing
        - Completed
        - Cancelled
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: By submitting this issue, you agree to our terms
      options:
        - label: I have the rights to share these streaming links
          required: true
        - label: The streaming links are publicly accessible
          required: true