name: Add Movie
description: Add a new movie to the repository
title: "[ADD-MOVIE] Movie Title (Year)"
labels: ["add-movie", "content"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing! Please fill out the form below to add a new movie.

  - type: input
    id: movie-title
    attributes:
      label: Movie Title
      description: Enter the full title of the movie
      placeholder: e.g., Avatar: The Way of Water
    validations:
      required: true

  - type: input
    id: movie-year
    attributes:
      label: Release Year
      description: Enter the year the movie was released
      placeholder: e.g., 2022
    validations:
      required: true

  - type: input
    id: source-info
    attributes:
      label: Source
      description: Where did you get these streaming links from?
      placeholder: e.g., GitHub Repository, Archive.org, Personal Collection
    validations:
      required: true

  - type: input
    id: primary-url
    attributes:
      label: Primary Streaming URL
      description: Main streaming link for the movie
      placeholder: https://archive.org/download/movie-name/movie.mp4
    validations:
      required: true

  - type: textarea
    id: alternative-urls
    attributes:
      label: Alternative URLs (Optional)
      description: Additional streaming links, one per line
      placeholder: |
        https://backup-site.com/movie.mp4
        https://mirror-site.org/movie.mp4
      rows: 4
    validations:
      required: false

  - type: input
    id: imdb-id
    attributes:
      label: IMDB ID (Optional)
      description: IMDB identifier (e.g., tt1234567)
      placeholder: tt1234567
    validations:
      required: false

  - type: input
    id: cover-url
    attributes:
      label: Cover/Poster URL (Optional)
      description: Link to movie poster image
      placeholder: https://example.com/poster.jpg
    validations:
      required: false

  - type: textarea
    id: movie-summary
    attributes:
      label: Summary (Optional)
      description: Brief description of the movie
      placeholder: A brief description of the movie plot...
      rows: 3
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: By submitting this issue, you agree to our terms
      options:
        - label: I have the rights to share these streaming links
          required: true
        - label: The streaming links are publicly accessible
          required: true