name: Add TV Series
description: Add a new TV series to the repository
body:
  - type: input
    attributes:
      label: Series Title
      description: Enter the full title of the TV series
      placeholder: e.g., Breaking Bad
  - type: input
    attributes:
      label: Release Year
      description: Enter the year the series started
      placeholder: e.g., 2008
  - type: input
    attributes:
      label: Source
      description: Where did you get this series? (e.g., Netflix, Disney+)
      placeholder: e.g., Netflix
  - type: textarea
    attributes:
      label: Episode URLs
      description: Enter streaming URLs for episodes (one per line)
      placeholder: |
        https://example.com/s01e01.m3u8
        https://example.com/s01e02.mp4
        https://example.com/s01e03.mkv